### ISSUE TITLE
Bootstrap theming

### ISSUE THREAD

**Issue by jmagnuss** [maineventio/dashwork#2]
How do I install a bootstrap theme?  Currently I see custom CSS in public/app/css/style.css, but I’d like to be able to use bootstrap themes instead of custom overrides.

**Comment by GaurangGhinaiya** [comment]
For now i add the theme i have and its in bootstrap.
Later i will change theme provided by you

**Comment by jmagnuss** [comment]
Sure, please install this theme, so I can see how an external theme is added:
https://github.com/almasaeed2010/AdminLTE

From their README:

There are multiple ways to install AdminLTE.

Using The Command Line:
Github
Fork the repository (here is the guide).
Clone to your machine
git clone https://github.com/YOUR_USERNAME/AdminLTE.git
Bower
bower install admin-lte
Composer
composer require "almasaeed2010/adminlte=~2.0"

**Comment by GaurangGhinaiya** [comment]
ok i will do it after 19th Jan
Because i am on vacation till 19th jan.

**Comment by GaurangGhinaiya** [comment]
I change the theme
